language: c

matrix:
  include:
    - script: make
      compiler:
        - clang
        - gcc
    - script: "rm -rf build && mkdir build && cd build && cmake .. && make"
      compiler:
        - clang
        - gcc
